# Generated by Django 3.2.20 on 2023-09-06 06:03

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedCountryLimitMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=7)),
                ('component_type', models.CharField(max_length=255)),
                ('usage_during_month', models.IntegerField()),
                ('usage_since_beginning_of_year', models.IntegerField()),
            ],
            options={
                'db_table': 'aggregated_country_limit_metrics',
            },
        ),
        migrations.CreateModel(
            name='AggregatedCountryUsageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=7)),
                ('component_type', models.CharField(max_length=255)),
                ('usage_during_month', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('usage_since_beginning_of_year', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'db_table': 'aggregated_country_usage_metrics',
            },
        ),
    ]
