# Generated by Django 3.2.20 on 2023-10-05 11:10

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waldur_metrics', '0002_aggregatedcountryquotametric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLimit',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                ('date', models.DateField()),
                ('resource_name', models.CharField(max_length=255)),
                ('resource_uuid', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('project_uuid', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_uuid', models.CharField(max_length=255)),
                ('limit_name', models.CharField(max_length=255)),
                ('limit_value', models.IntegerField()),
            ],
            options={
                'db_table': 'resource_limits',
            },
        ),
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                ('date', models.DateField()),
                ('resource_name', models.CharField(max_length=255)),
                ('resource_uuid', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('project_uuid', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_uuid', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                (
                    'usage',
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    'usage_since_creation',
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
            ],
            options={
                'db_table': 'resource_usages',
            },
        ),
    ]
