# Generated by Django 3.2.20 on 2024-06-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waldur_metrics', '0004_delete_resourceusage_duplicates'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourceusage',
            unique_together={
                ('date', 'resource_uuid', 'project_uuid', 'customer_uuid', 'type')
            },
        ),
    ]
